jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - checkout      
      - run: Set-LocalUser -Name "Administrator" -Password (ConvertTo-SecureString -AsPlainText "Akuhnet123" -Force)
      - run: Get-LocalUser -Name "Administrator" | Enable-LocalUser 
      - run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
      - run: tar xf ngrok.zip
      - run: Copy ngrok.exe C:\Windows\System32
      - run: cmd /c echo ./ngrok.exe authtoken "1szrzOH5iAnVvjdLA9sjELGcrmM_3wcb9xfGs3JvpPAtYmhNf" >a.ps1
      - run: cmd /c echo cmd /k start ngrok.exe tcp 3389 >>a.ps1
      - run: cmd /c echo ping -n 999999 10.10.10.10 >>a.ps1
      - run: .\a.ps1
